name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hi, world!

                       
      - name: Download artifact from build
        uses: bettermarks/action-artifact-download@0.3.0
        with:
         repo: sreesar/office
         token: ${{ secrets.GITHUB_TOKEN }}
         artifact_name: my-artifact
         rename: new-artifact-name    
         wait_seconds: 60
