name: Artifcate_create
on: push 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
   
    - name: 'Build Artifact file'
      uses: actions/upload-artifact@v3
      with:
       name: my-artifact1
       path: Dockerfile
       retention-days: 5
    - name: Download artifact from build
      uses: bettermarks/action-artifact-download@0.3.0
      with:
        repo: sreesar/office
        token: ${{ secrets.GITHUB_TOKEN }}
        artifact_name: my-artifact1
        rename: new-artifact    
        wait_seconds: 60
