name: Artifcate_create
on: push 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
        
    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: artifact_push.yml
        workflow_conclusion: success
        branch: main
       # Optional, defaults to all types
        
        # Optional, will use specified workflow run
       
    # Optional, run number from the workflow
        run_number: 17
        name: my-artifact1
        path: sreesar/office/.
    # Optional, defaults to current repo
        repo: ${{ github.repository }}
        check_artifacts:  false
        search_artifacts: false
        skip_unpack: false
        if_no_artifact_found: fail
        
    - name: check files 
      run: ls -alr && tree
        
    - name: Pushes test file
      uses: antoineVIVIES/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_files: 'sreesar/office/my-artifact1'
        destination_repo: 'sreesar/project'
        destination_folder: './'
        user_email: 'ninanarmatha0389@gmail.com'
        user_name: 'sreesar'
        commit_message: 'Artifact file push to project repo'
