on: [push]
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: test job
    steps:
      - name: environment step
        uses: sreesar/my_actions@main
       
      # Use the output from the `hello` step
      - name: Get output 
        run: python --version && tsc --version && node --version && npm --version
        
