name: Push File

on: 
 workflow_dispatch: {}
 push:
  branches: 
   - main
jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    
    - name: Pushes test folder
    - uses: actions/checkout@v2.3.4
    - uses: GuillaumeFalourd/copy-push-files@v1
      with:
          email: ninanarmatha0389@gmail.com
          name: sreesar
          commit_message: push the file
          target_branch: main
          source_files: ./.github/workflows/copy.yml
          remote_repository: https://github.com/sreesar/project.git
          access_token: ${{ secrets.key }}
