name: samplecode
on: [push]
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: test job
    steps:
      - name: github code check out
        uses: actions/checkout@v2
       
     
      - name: install npm
        run: npm install @playwright/test
