name: Pipeline Name

on:
 workflow_dispatch: {}
jobs:

 notify:
    runs-on: ubuntu-latest
    if: always()
    steps:
    - name: Send a Notification
      id: notify
      uses: sreesar/teams@main
      with:
        teams_webhook_url: ${{ secrets.TEAM_HOOK }}
        message: "Github Action Build Number ${{ github.run_number }} Completed for ${{ github.repository }} and the outcome is  ${{ needs.build.result }}."
